from __future__ import annotations

import os
from typing import Any


def build_explanation(mode: str, request_payload: dict[str, Any], result_payload: dict[str, Any]) -> str:
	api_key = os.getenv("GEMINI_API_KEY")
	model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

	prompt = (
		"You are a concise calculus tutor. Explain this solution in clear steps, mention method used, "
		"and if symbolic solving has limits, state it plainly.\n\n"
		f"Mode: {mode}\n"
		f"Input: {request_payload}\n"
		f"Result: {result_payload}\n"
	)

	if api_key:
		try:
			from google import genai

			client = genai.Client(api_key=api_key)
			response = client.models.generate_content(model=model_name, contents=prompt)
			text = getattr(response, "text", None)
			if text:
				return text.strip()
		except Exception:
			pass

	return (
		"Explanation service is running in fallback mode (no API key configured yet). "
		"The symbolic result was generated by SymPy using the selected calculus mode."
	)
